[package]
name = "site2md_secrss"
version = "0.1.0"
edition = "2024"

[dependencies]
clap.workspace = true
htmd.workspace = true
scraper.workspace = true
serde.workspace = true
tokio.workspace = true
wreq.workspace = true
wreq-util.workspace = true

[dev-dependencies]
brotli.workspace = true
insta.workspace = true
